### ISSUE TITLE
Insert embedded document

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#778] opened 2023-01-17 19:08 UTC
### OS: MacOS 12.6

 am trying to insert a document type into a embedded property. While the operation completes, the type of the inserted document is `MAP` and not `EMBEDDED`.

## Expected behavior
`EMBEDDED`

## Actual behavior
`MAP`

## Steps to reproduce
```
CREATE DOCUMENT TYPE pair;
CREATE PROPERTY pair.head STRING;
CREATE PROPERTY pair.tail EMBEDDED;

INSERT INTO pair CONTENT { 'head': 'hi', 'tail': { '@type': 'pair', 'head': 'ho', 'tail': null } };
INSERT INTO pair (head, tail) VALUES ('head', { '@type': 'pair', 'head': 'ho', 'tail': null });

SELECT tail.type() FROM pair;
```
There is an SQL-Insert example which suggests this should work: https://docs.arcadedb.com/#SQL-Insert

**Comment by lvca** [comment] 2023-01-17 20:26
Reproduced.

**Comment by lvca** [comment] 2023-01-18 01:49
Fixed

**Comment by gramian** [comment] 2023-01-19 17:12
@lvca Just tested on current head ([6462cb9](https://github.com/gramian/arcadedb/commit/6462cb9810590de1ffae9e6d59cb95dda9024e7d)) and running the code above returns type `<null>`, is this correct?

Also, a follow-up: If I leave `'@type': 'pair'` out, I get an error (`Cannot execute command Cannot convert type 'class java.util.HashMap' to 'EMBEDDED' found in property 'tail'`), which is on the one hand understandable but on the other hand the keys and types of values match the constraint type. Shouldn't
```
INSERT INTO pair CONTENT { 'head': 'hi', 'tail': { 'head': 'ho', 'tail': null } };
```
be accepted, too?

**Comment by lvca** [comment] 2023-01-20 05:50
ArcadeDB couldn't know with type is embedded, because it's not declared in the schema that pair.tail is a pair itself.

**Comment by gramian** [comment] 2023-01-20 07:56
@lvca I probably assumed the passed `@type` would be taken. But could it be known that it is of general type `EMBEDDED` so that `EMBEDDED` could be returned instead of `null`?

What about inserting any JSON and being accepted as embedded document, I mean without having `@type` in the object?

**Comment by lvca** [comment] 2023-02-01 23:06
if there is no type, no document can't be created because all the document/vertex/edge instances require a type. It can be created as an EMBEDDED MAP (Map type) like it's already doing.

Closing this issue.

**Closed by lvca** 2023-02-01 23:06 UTC
Labels: bug
