### ISSUE TITLE
Replication Error

### ISSUE THREAD

**Issue by psytron** [ArcadeData/arcadedb#779] opened 2023-01-17 19:09 UTC
## Expected behavior
Play with Data style smooth sync of all machines. Automatic self configuration when a user points to replication target. 

## Actual behavior
Error: 
<img width="419" alt="ha_error" src="https://user-images.githubusercontent.com/7834453/212989147-d3d31e5e-66bd-4ea5-88c2-2bb7af20d2c9.png">

## Steps to reproduce
Click on Replication screen and Connect Button. 
Add address of another fully operational fresh ArcadeDB server.

**Comment by lvca** [comment] 2023-01-17 19:53
I can't reproduce this exact issue, but it looks like ArcadeDB wasn't started with HA enabled. Try setting:

```
-Darcadedb.ha.enabled=true
```

At startup. I'm going to look closely to the exception and provide a better error, at least.

**Comment by lvca** [comment] 2023-01-17 19:58
Ok, just changed the message to `ArcadeDB is not running with High Availability module enabled. Please add this setting at startup: -Darcadedb.ha.enabled=true`

**Comment by psytron** [comment] 2023-01-18 18:25
When I set  
-Darcadedb.ha.enabled=true 
the docker container does not seem to start anymore:

generic-arcade-1  | Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.arcadedb.server.ha.HAServer.isLeader()" because the return value of "com.arcadedb.server.ArcadeDBServer.getHA()" is null
generic-arcade-1  | 	at com.arcadedb.server.ha.ReplicatedDatabase.command(ReplicatedDatabase.java:577)
generic-arcade-1  | 	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:411)
generic-arcade-1  | 	at com.arcadedb.server.ArcadeDBServer.loadDefaultDatabases(ArcadeDBServer.java:471)
generic-arcade-1  | 	at com.arcadedb.server.ArcadeDBServer.start(ArcadeDBServer.java:129)
generic-arcade-1  | 	at com.arcadedb.server.ArcadeDBServer.main(ArcadeDBServer.java:90)
^[[B

**Comment by lvca** [comment] 2023-01-18 20:16
Reproduced. Working on it.

**Comment by lvca** [comment] 2023-01-18 20:45
Changed the order of when imported databases are loaded. Tested with the docker and works.

**Comment by psytron** [comment] 2023-01-18 21:37
Ok. Pulled latest. Now when I try to add replication target the window disappears and nothing happens: 
<img width="872" alt="quorum" src="https://user-images.githubusercontent.com/7834453/213300400-59088c3b-6061-4cad-b1d6-d16b3e03e953.png">

**Comment by psytron** [comment] 2023-01-18 21:41
Also. In my humble opinion for a maximum PlayWithData approach, most users would love to skip the part where you have to think about "HA configuration" or "leader election".

**Comment by psytron** [comment] 2023-01-18 21:54
Also:  The little pop-up window which says "Connect to a cluster" :
After a user clicks "Send" The window *disappears* and then the configuration is gone....
No user feedback. No acknowledgement of any kind that time was just invested. 
The pop-up window just disappears and nothing happens.  
This is a very frustrating UX because it makes you feel like Arcade is wasting your time and black-holing valuable configuration investments. 
It would be great if (at the very least) it would store and display a line item showing the data which was entered. 
Even if it fails with errors it would be great to reflect the work that was just done..

**Comment by lvca** [comment] 2023-01-19 15:41
it's a good idea to save the latest input and pre-fill it every time.

About the leader election, there's nothing a user can do: the election is executed by the servers automatically.

You should receive a popup immediately after sending the command that the command was processed. It should be top right of the screen and it remains open for like 5 seconds. In case of errors, it's a red popup with the detail of the problem.

**Comment by psytron** [comment] 2023-01-21 22:56
Just updated to latest image:
 v23.1.2-SNAPSHOT (build 477a660217e52d495eea0fcbd2bbe588fa90306d/1674253051356/main)

In our opinion the workflow is still pretty glitchy. 
Clicking the "Send" button leaves you with zero user feedback while the daemon figures out if it worked or not. So it still feels like it's black-holing use input. 
This is just our opinion though. You have a lot of great concepts in this product and I suppose you have other priorities.  This is just feedback.

**Comment by lvca** [comment] 2023-01-29 23:32
Thanks for the feedback. The `connect` in the studio should return immediately feedback, in case of success or error.

**Comment by lvca** [comment] 2023-02-01 23:07
Closing this issue, but please feel free to further comment if you have any ideas to improve the current workflow after you tried the upcoming 23.1.2!

**Closed by lvca** 2023-02-01 23:07 UTC
Labels: bug
