### ISSUE TITLE
Database backup command no longer works after 23.5.1 update

### ISSUE THREAD

**Issue by allegrojm** [ArcadeData/arcadedb#1115] opened 2023-06-07 03:26 UTC
### ArcadeDB Version:
ArcadeDB Server v23.5.1-SNAPSHOT (build a9645351492ab72f95da2d6403e9deb34f405689/1686012261898/main)
### OS and JDK Version:
Running on Linux 3.10.0-1160.62.1.el7.x86_64 - OpenJDK 64-Bit Server VM 11.0.17 ((Red_Hat-11.0.17.0.8-2.el7_9))

### Expected behavior
That the database backup will work.

### Actual behavior
2023-06-07 03:16:59.701 INFO  [arcadedb] <OhioServer> [OVariableParser.resolveVariables] Error on resolving property: arcadedb.server.rootPath<OhioServer> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandExecutionException: Error on backing up database
        at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:79)
        at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
        at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:55)
        at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:95)
        at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:59)
        at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:45)
        at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:39)
        at com.arcadedb.query.sql.SQLScriptQueryEngine.executeInternal(SQLScriptQueryEngine.java:223)
        at com.arcadedb.query.sql.SQLScriptQueryEngine.command(SQLScriptQueryEngine.java:110)
        at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1284)
        at com.arcadedb.server.ha.ReplicatedDatabase.command(ReplicatedDatabase.java:609)
        at com.arcadedb.server.ha.ReplicatedDatabase.command(ReplicatedDatabase.java:595)
        at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:436)
        at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:118)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:87)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:98)
        at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:127)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.arcadedb.integration.backup.BackupException: Error during backup of database 'iconlookup' to file 'iconlookup-backup-20230607-031659702.zip'
        at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:72)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:67)
        ... 23 more
Caused by: com.arcadedb.integration.backup.BackupException: The backup file '/backups/iconlookup/iconlookup-backup-20230607-031659702.zip' cannot be created
        at com.arcadedb.integration.backup.format.FullBackupFormat.backupDatabase(FullBackupFormat.java:60)
        at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:66)
        ... 28 more

### Steps to reproduce
BACKUP DATABASE command

**Comment by gramian** [comment] 2023-06-07 07:08
Hi.
Did it work in 23.4.1 last or an earlier version?
This may be a regression introduced with the `server.backupDirectory` setting. Particularly the default path ([see here](https://github.com/ArcadeData/arcadedb/blob/main/engine/src/main/java/com/arcadedb/GlobalConfiguration.java#L270)). Can you test the `BACKUP DATABASE` command with custom path and/or the command line setting mentioned above? I will test this, too, later.

**Comment by allegrojm** [comment] 2023-06-07 16:47
It was working OK in 23.3.1 which is what we just upgraded from to 23.5.1 on 5/29. We use simply use the BACKUP DATABASE from a node.js app using sqlscript command over http. Nothing appended to the  BACKUP DATABASE command will work. Please fix this regression.

**Comment by gramian** [comment] 2023-06-07 17:49
Dear @allegrojm ,
I am sorry but I cannot reproduce your error with the latest repository head. Maybe a recent commit fixes your problem already? Could you try with the latest state of the `23.5.1-SNAPSHOT`.

**Comment by allegrojm** [comment] 2023-06-07 18:34
Not a good answer. We just updated a few days ago because of an other bug. We will not just add update because you think it might solve an issue you can't reproduce. Please figure out what the regression is and FIX it.

**Comment by gramian** [comment] 2023-06-07 18:43
Dear @allegrojm ,
I am sure you are aware of this, but version `23.5.1` is under development. The [latest stable release](https://github.com/ArcadeData/arcadedb/releases) is version `23.4.1`. Is there a particular reason you are using the development head and not the latest stable version, maybe a certain feature?

Maybe some more information can help clearing this up: Are you running ArcadeDB in a container, and what commandline parameters are you using?

**Comment by lvca** [comment] 2023-06-07 18:50
The issue is that can't resolve the root path:

```
Error on resolving property: arcadedb.server.rootPath
```

Following @gramian response, how do you start the server?

**Comment by allegrojm** [comment] 2023-06-07 18:54
gramain,  we are using 23.5.1 because Luca added a fix to a serious bug related to replication and put it into 23.5.1.

**Comment by allegrojm** [comment] 2023-06-07 18:56
https://github.com/ArcadeData/arcadedb/commit/a9645351492ab72f95da2d6403e9deb34f405689 is why we are using 23.5.1 just so you know.

**Comment by gramian** [comment] 2023-06-07 18:56
As an immediate workaround you could try using the `server.backupDirectory` setting, until this is fixed.

**Comment by lvca** [comment] 2023-06-07 18:58
Just compiled from the latest main, run a brand new fresh server.sh and created a database with 1 record, then executed `backup database` from studio and works. Is it possible you have a modified `server.sh` file? Can you please check the differences with the default one?

@gramian I fixed https://github.com/ArcadeData/arcadedb/issues/1114 and hence they run on the latest snapshot.

**Comment by allegrojm** [comment] 2023-06-07 19:01
we never change the default server.sh

**Comment by lvca** [comment] 2023-06-07 19:10
After a chat on discord the issue seems to be with using "sqlscript" as a language. I was able to reproduce the same issue by selecting "sqlscript" from studio. Working to a fix.

**Comment by lvca** [comment] 2023-06-07 19:19
Fixed in `main`.

**Comment by allegrojm** [comment] 2023-06-07 21:27
tested and it works again.

**Comment by lvca** [comment] 2023-06-08 03:45
Reopened because new test cases show the issue can still happens from a distributed setup.

**Comment by lvca** [comment] 2023-06-08 03:46
Fixed with the latest commit.

**Closed by lvca** 2023-06-08 03:46 UTC
Labels: bug, bug fixed
