### ISSUE TITLE
Syntax error on executing query: Record #208:73 not found

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#951] opened 2023-03-17 08:54 UTC
### ArcadeDB Version: v23.2.1

There's been a fair amount of times I get this error, generally during cypher read queries. It's not common, but it happens maybe like once an hour or something. However, it's not blocking. When it happens, I `ROLLBACK` that transaction and everything is fine.

Do you know what it could be relating to or why it might be happening? Alternatively, is there any way / place I can look to debug this?

So far, from some of the logs I've been seen in my application, it could be happening when two sessions call queries that overlap, but I'm not sure.

**Comment by lvca** [comment] 2023-03-17 22:18
Usually, when a record is not found with Gremlin or Cypher it's because you're crossing an edge that doesn't exist anymore or is connected to a vertex that has been deleted. If you always use bidirectional edges, this should never happen, because ArcadeDB takes care of keeping the graph consistent in a transaction.

Is this the case? Are you using unidirectional edges?

Otherwise, it could be an index that is not synchronized and points to a deleted record? We fixed an issue with indexes 2-3 months ago, so if you have used an old version I suggest to rebuild all the indexes (you can execute this from the console/studio once: `rebuild index *`). 

But in both cases above, the fact that the record exists (208:73) means this case is different. I never experience such an error, I'd love a way to reproduce it.

I don't think it's a race condition, because ArcadeDB has a strong separation of pages in transactions (threads) with no objects shared between threads (but the immutable pages).

**Comment by lvca** [comment] 2023-06-09 00:44
Any news on this? Closing this issue as resolved. In case please comment here to be reopened.

**Closed by lvca** 2023-06-09 00:44 UTC
