### ISSUE TITLE
Unable to run queries using PostgresProtocolPlugin

### ISSUE THREAD

**Issue by scwagner** [ArcadeData/arcadedb#215] opened 2021-11-19 14:31 UTC
## Expected behavior
Connecting using the Postgres official command-line client with the PostgresProtocolPlugin driver install will work.

## Actual behavior
Any queries attempted to be run against the database return an error "Error on executing query: null"

## Steps to reproduce
Running the latest version of ArcadeDB from Docker Hub:
> docker run --pull always -d --rm --name arcadedb -v `pwd`/data:/home/arcadedb/databases -p 6379:6379 -p 5432:5432 -p 2480:2480 -p 2424:2424 --env arcadedb.server.rootPassword=playwithdata --env arcadedb.server.plugins="Redis:com.arcadedb.redis.RedisProtocolPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin" arcadedata/arcadedb:latest

Attempting to connect and run a command using official `psql` command line client:
> $ psql -U root -h 127.0.0.1 game_1_0
> Password for user root:
> psql (10.19 (Ubuntu 10.19-0ubuntu0.18.04.1), server 10.5)
> Type "help" for help.
>  
> game_1_0=> select from Item;
> ERROR:  Error on executing query: null

**Comment by lvca** [comment] 2021-11-19 15:13
We used psql client to develop the driver initially, then we switched to the Java official JDBC driver so we can have automatic tests and regression tests, but it looks like the protocol is quite wide and we have to check again with psql what's going on. I guess we have to change slightly the behavior based on the client type.

**Comment by lvca** [comment] 2021-11-19 15:24
From a quick test seems to work with the simple database used for testing Postgres when I'm connecting through psql:

```
arcadedb % psql -U root -h 127.0.0.1 postgresdb
Password for user root:
psql (14.0, server 10.5)
Type "help" for help.

postgresdb=> select from schema:types
postgresdb-> ;
  name  |   type   | parentTypes | properties |     indexes
--------+----------+-------------+------------+------------------
 E1     | edge     | []          | []         | []
 E2     | edge     | []          | []         | []
 Person | document | []          | []         | []
 V1     | vertex   | []          | [{ id: 0  +| [{ name: V1[id] +
        |          |             | name: id  +| typeName: V1    +
        |          |             | type: LONG+| type: LSM_TREE  +
        |          |             |  }]        | properties: [id]+
        |          |             |            | automatic: true +
        |          |             |            | unique: true    +
        |          |             |            |  }]
 V2     | vertex   | []          | []         | []
(5 rows)

postgresdb=> select from V1;
 id | name
----+------
    | V1
(1 row)

postgresdb=> select from Person;
postgresdb=> select from V2;
 name
------
 V2
 V3
(2 rows)

postgresdb=>
```

**Comment by lvca** [comment] 2021-11-19 15:34
Found the error. When the query returns many records I got `ERROR:  Error on executing query: null`. If you do the same select with the limit works. So there must be an issue with the management of pagination.

**Comment by lvca** [comment] 2021-11-19 22:25
Fixed by https://github.com/ArcadeData/arcadedb/commit/1dc352addaaa741a54f81af401f17ab181d7b26c.

**Comment by lvca** [comment] 2021-11-19 22:26
@scwagner the issue was with the buffer allocated for sending the result back to the client. Now it's fixed. Thanks for reporting it (and to be a sponsor!).

**Closed by lvca** 2021-11-19 22:25 UTC
Labels: bug

**Comment by scwagner** [comment] 2021-11-21 05:42
@lvca Thanks I can confirm that with the latest image from Docker Hub I am able to connect with both `psql` and using JDBC.  Thank you for the quick fix!
