### ISSUE TITLE
List of buckets in query not working

### ISSUE THREAD

**Issue by ficu88** [ArcadeData/arcadedb#671] opened 2022-12-14 18:20 UTC
ArcadeDB Version: v22.12.1-SNAPSHOT
JDK Version: openjdk 11.0.17 2022-10-18
OS: Ubuntu 22.04.1 LTS

## Expected behavior
As from the documentation when I launch this `SELECT FROM BUCKET:Customer_Europe_Italy,Customer_Europe_Spain` I expect to see the results (empty or data).

## Actual behavior
```
<ArcadeDB_0> Error on command execution (PostCommandHandler)
com.arcadedb.exception.CommandSQLParsingException: com.arcadedb.query.sql.parser.ParseException: Encountered " <SELECT> "SELECT "" at line 1, column 1.
Was expecting one of:
    <WHILE> ...
    <IF> ...
    <FOREACH> ...
    ";" ...

        at com.arcadedb.query.sql.executor.SQLEngine.parseScript(SQLEngine.java:110)
        at com.arcadedb.query.sql.executor.SQLEngine.parseScript(SQLEngine.java:102)
        at com.arcadedb.database.EmbeddedDatabase.execute(EmbeddedDatabase.java:1243)
        at com.arcadedb.server.ServerDatabase.execute(ServerDatabase.java:415)
        at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:100)
        at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:71)
        at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:85)
        at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:109)
        at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: com.arcadedb.query.sql.parser.ParseException: Encountered " <SELECT> "SELECT "" at line 1, column 1
```

## Steps to reproduce

```shell
docker run -d --rm  -p 2480:2480 -p 2424:2424 -p 6379:6379 -p 5432:5432 -p 8182:8182 \
--name arcadedb \
--env JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata \
-Darcadedb.serverMetrics=true \
-Darcadedb.server.plugins=Redis:com.arcadedb.redis.RedisProtocolPlugin,MongoDB:com.arcadedb.mongo.MongoDBProtocolPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin,GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin " \
arcadedata/arcadedb:latest
```
Follow (bucket guide)[https://docs.arcadedb.com/#Buckets] to reproduce.

Thank You.

**Comment by lvca** [comment] 2022-12-14 19:31
I think the issue is in the docs. This should work:

```sql
SELECT FROM BUCKET:[Customer_Europe_Italy,Customer_Europe_Spain]
```

In the case of multiple buckets, the list syntax is required with squared brackets.

**Comment by ficu88** [comment] 2022-12-15 08:21
Yes it works, thank you.

**Comment by lvca** [comment] 2022-12-15 15:58
I guess we need to improve the docs on that ;-)

**Comment by lvca** [comment] 2022-12-15 15:59
@gramian already did it, ok we can close this issue then.

**Closed by lvca** 2022-12-15 15:59 UTC
Labels: documentation
