### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by shasaur** [ArcadeData/arcadedb#851] opened 2023-02-09 22:36 UTC
So I'm just trying to export the database and I'm getting an error that I'm in a transaction? (Even when I re-open the DB). Does it work for you guys? (I'm on the latest release)

com.arcadedb.exception.CommandExecutionException: Error on exporting database                                                                                                                                              at com.arcadedb.query.sql.parser.ExportDatabaseStatement.executeSimple(ExportDatabaseStatement.java:86)                                                                                                            at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)                                                                                                            at com.arcadedb.query.sql.parser.SimpleExecStatement.execute(SimpleExecStatement.java:63)                                                                                                                          at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:85)                                                                                                                                              at com.arcadedb.query.sql.parser.Statement.execute(Statement.java:69)                                                                                                                                              at com.arcadedb.query.sql.SQLQueryEngine.command(SQLQueryEngine.java:106)                                                                                                                                          at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1250)                                                                                                                                      at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)                                                                                                                                             at com.arcadedb.server.http.handler.PostCommandHandler.executeCommand(PostCommandHandler.java:127)                                                                                                                 at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:88)                                                                                                                         at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:91)                                                                                                               at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)                                                                                                                        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)                                                                                                                                           at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)                                                                                                                                        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)                                                                                                                                              at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)                                                                                                                               at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)                                                                                                                         at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)                                                                                                                                           at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                                         Caused by: com.arcadedb.integration.exporter.ExportException: Error on writing to 'exports\Movies.graphson.tgz'                                                                                                            at com.arcadedb.integration.exporter.Exporter.exportDatabase(Exporter.java:101)                                                                                                                                    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                        at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                                                      at com.arcadedb.query.sql.parser.ExportDatabaseStatement.executeSimple(ExportDatabaseStatement.java:79)                                                                                                            ... 18 more                                                                                                                                                                                                **Caused by: com.arcadedb.integration.exporter.ExportException: Transaction in progress found**                                                                                                                                at com.arcadedb.integration.exporter.format.JsonlExporterFormat.exportDatabase(JsonlExporterFormat.java:62)                                                                                                        at com.arcadedb.integration.exporter.Exporter.exportDatabase(Exporter.java:78)                                                                                                                                     ... 23 more

**Comment by lvca** [comment] 2023-02-10 00:26
@shasaur are you executing the export from Studio/HTTP API, console or API?

**Comment by shasaur** [comment] 2023-02-10 09:09
Just from the Studio.

**Comment by shasaur** [comment] 2023-02-10 09:55
Seems like the actual export button itself is working though, I was just trying to run the SQL query. So I'll use the button for now.

**Comment by shasaur** [comment] 2023-02-10 10:07
Oh wait, the button doesn't actually do a full export. Nevermind.

**Comment by lvca** [comment] 2023-02-10 18:04
The exporter has this check tha cannot be run if a transaction is active (because of partial, not committed data will not be exported), but the HTTP server handler could start a new transaction, so this is an actual issue. Working on it.

**Comment by lvca** [comment] 2023-02-10 18:06
Reproduced/

**Comment by lvca** [comment] 2023-02-10 18:11
Fixed in `main` branch.

**Closed by lvca** 2023-02-10 18:11 UTC
Labels: bug

**Comment by shasaur** [comment] 2023-02-10 22:38
Cool - that was fast. Nice work!
