### ISSUE TITLE
SQL: Listing indices via `SELECT FROM schema:indexes` errors

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#884] opened 2023-02-22 16:25 UTC
## Expected behavior
?

## Actual behavior
```
Cannot execute command Object of type class java.util.Collections$UnmodifiableRandomAccessList not supported
```

<details>

```
Error on command execution (PostCommandHandler)
java.lang.IllegalArgumentException: Object of type class java.util.Collections$UnmodifiableRandomAccessList not supported
	at com.arcadedb.serializer.json.JSONObject.objectToElement(JSONObject.java:341)
	at com.arcadedb.serializer.json.JSONArray.put(JSONArray.java:154)
	at com.arcadedb.serializer.JsonSerializer.serializeResult(JsonSerializer.java:135)
	at com.arcadedb.server.http.handler.AbstractQueryHandler.serializeResultSet(AbstractQueryHandler.java:102)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:95)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:92)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Steps to reproduce
```
SELECT FROM schema:indexes
```

**Comment by allegrojm** [comment] 2023-02-24 16:12
Although a different command, SELECT indexes from schema:types worked for me

**Comment by lvca** [comment] 2023-03-01 00:48
@gramian how is the index structured? Could you please provide the output from @allegrojm's comment?

```
SELECT indexes from schema:types
```

I suspect it would return an error because the problem is in the JSON serializaton and not the command per se.

**Comment by lvca** [comment] 2023-03-01 00:54
Checked the code and the list of list and map of string/list in JSON serialization was not supported, and that was the output of the indexes. So it should be 99% fixed with the last commit. Please confirm.

**Closed by lvca** 2023-03-01 00:54 UTC
Labels: bug

**Comment by gramian** [comment] 2023-03-01 14:08
It works for me now. Thank you!
