### ISSUE TITLE
DEFAULT with function call only works with ALTER PROPERTY

### ISSUE THREAD

**Issue by TimMensch** [ArcadeData/arcadedb#1609] opened 2024-05-20 17:17 UTC
### ArcadeDB Version:

`v24.4.1 (build c714a4f5c827d742d6edd0f7788fe049bc63607b/1713579699346/main)`

### OS and JDK Version:

`Running on Linux 5.15.146.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM 11.0.22 (Temurin-11.0.22+7)`

### Expected behavior

Setting `DEFAULT sysdate()` during create should be identical to adding `DEFAULT sysdate()` during ALTER PROPERTY.

### Actual behavior

When I say:

```
CREATE VERTEX TYPE Test;
CREATE PROPERTY Test.createdAt IF NOT EXISTS DATETIME (mandatory true, readonly, DEFAULT sysdate());
CREATE VERTEX Test; -- Wait a couple of seconds
CREATE VERTEX Test; -- Wait a couple of seconds 
CREATE VERTEX Test;
```

The three vertices all have the same createdAt field. Whereas if I say:

```
ALTER PROPERTY Test.createdAt DEFAULT sysdate();
```

Then 

```
CREATE VERTEX Test;  -- Wait a couple of seconds
CREATE VERTEX Test;  -- Wait a couple of seconds
CREATE VERTEX Test;
```

...creates vertices with three unique timestamps.

I'm using the Docker Hub image version 24.4.1.

_Originally posted by @TimMensch in https://github.com/ArcadeData/arcadedb/issues/905#issuecomment-2118528446_

**Comment by gramian** [comment] 2024-05-20 17:33
Hmm, I can reproduce this. It seems the timestamp in the first case is the creation date of the property, not the vertex.

Could you try:
```
CREATE PROPERTY Test.createdAt IF NOT EXISTS DATETIME (mandatory true, readonly, DEFAULT `sysdate()`);
```
this seems to work for me.

**Comment by TimMensch** [comment] 2024-05-20 19:42
OK, sure, that works. Thanks.

**Comment by lvca** [comment] 2024-05-21 17:22
Probably the docs are not clear on this point?

**Comment by lvca** [comment] 2024-05-21 17:35
Ok, I haven't seen this from @gramian https://github.com/ArcadeData/arcadedb/pull/1611. Now it should be fixed.

**Comment by gramian** [comment] 2024-10-30 08:55
@lvca It looks like this problem came back.

**Closed** 2024-10-30 09:08 UTC
Labels: bug, fixed

**Comment by gramian** [comment] 2024-10-30 09:11
Sorry false alarm, but there is something related not right I cannot yet pin down.
