### ISSUE TITLE
 http://ba22dc1c703a:2480  change on http://localhost:2480

### ISSUE THREAD

**Issue by Lyumih** [ArcadeData/arcadedb#1271] opened 2023-10-13 09:40 UTC
2023-10-13 09:37:23.080 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://ba22dc1c703a:2480  
![image](https://github.com/ArcadeData/arcadedb/assets/32732179/b5ea69d8-af75-49ee-a812-fd08af3a27bc)

**Comment by gramian** [comment] 2023-10-13 11:03
Hi,
I assume you are running an ArcadeDB container. The name printed in the logs is the container's host name in Docker's network. For all practical purposes, you can still use `http://localhost:2480` on your desktop to reach the server, as Docker (if you run the Docker hub image) makes the container and port visible. Using the local name instead of hard coding `localhost` (which in your case would actually mean local to your container not your desktop), would be problematic when running multiple servers.

If you just want to change the container's host name you can add the `--hostname my_arcadedb` option to the Docker command.

**Comment by lvca** [comment] 2023-10-31 20:43
Closing this issue. If the issue is still there, please comment here.

**Closed by lvca** 2023-10-31 20:43 UTC
