### ISSUE TITLE
Adding constraints to properties

### ISSUE THREAD

**Issue by aschoijett** [ArcadeData/arcadedb#517] opened 2022-09-18 15:23 UTC
## Expected behavior
Syntax for the CREATE PROPERTY and ALTER PROPERTY commands work as shown in the manual.   
This is is not the case. 

## Actual behavior
CREATE VERTEX TYPE FirstVertex
- works fine

CREATE PROPERTY FirstVertex.CreatedOn  ( readonly true ) (or READONLY TRUE)
- fails saying
> Error on execution of the command.   The property is created though.

Note that the same command typed without the constraint works fine
CREATE PROPERTY FirstVertexTtype.UpdatedOn DATETIME

A similar problem occurs with the ALTER PROPERTY command:
ALTER PROPERTY FirstVertexTtype.CreatedOn (READONLY true) 
- fails saying 

> Error o execution of the command. The property is not altered.   I can change its value in a previously created vertex. 

Note that there seems to be a similar discussion in #507 that was closed a few days ago, but I think the issue is still there. 

Many thanks,

**Comment by lvca** [comment] 2022-10-15 02:56
@aschoijett have you tried with a recent 22.9.1?

**Comment by aschoijett** [comment] 2022-10-16 02:37
Hi Luca.   Thank you for looking into this.  I just wanted to let you know
that I will not be proceeding with this project at this time.


Many thanks and best of luck. I think you have a great product!

Alex Schoijett
+1 647-924-7253

**Comment by lvca** [comment] 2022-10-16 04:42
Sorry to see you leaving, thanks for your contributions, and good luck with your projects.

**Comment by lvca** [comment] 2022-10-16 04:43
I am closing this issue because unable to reproduce it. In case anybody is experiencing this issue again, please comment this issue to be reopened.

**Closed by lvca** 2022-10-16 04:43 UTC
Labels: bug
