### ISSUE TITLE
[GremlinServer] Can't start without an error

### ISSUE THREAD

**Issue by JoJ123** [ArcadeData/arcadedb#1265] opened 2023-10-06 08:54 UTC
### ArcadeDB Version:
`v23.9.1`
### OS and JDK Version:
`Running on Windows 10 10.0 - OpenJDK 64-Bit Server VM 17.0.8.1 (Microsoft-8297089)`

### Expected behavior
Start ArcadeDB Server with GremlinServer Plugin

### Actual behavior
Failing with the following error message on the first start:
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/6085b838-1b6d-45bd-973c-f01230899715)

After Closing the script with Ctrl+C and restart: 
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/78950d8f-f914-4453-9f9c-2e72a586bbe5)
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/9921d4d8-bb25-400f-b371-ecc289b99bd2)

### Steps to reproduce
Unzip newest Version
Execute in Powershell:
`$env:JAVA_OPTS="-Darcadedb.server.rootPassword=playwithdata -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin"`
`./bin/server.bat`

**Comment by lvca** [comment] 2023-10-06 14:28
Have you tried to use docker? If it works with docker it must be something in how the script handles the paths in Windows. Just a first guess.

**Comment by JoJ123** [comment] 2023-10-06 16:52
Yes, it's working fine in docker

**Comment by lvca** [comment] 2023-10-06 17:28
So I guess there is something that causes the issue in the Gremlin server cfg in one of the following files under the `config` directory:

- gremlin-server.groovy
- gremlin-server.properties
- gremlin-server.yaml

Unfortunately, I don't have a Windows PC to test it out. Any chance you can lookup in those files if there is anything about paths?

**Comment by lvca** [comment] 2023-10-07 04:41
Try to run the script from the ArcadeDB home directory with: `bin\server.bat`

**Comment by JoJ123** [comment] 2023-10-07 07:30
Seems to be still the same issue. I've taken the latest version from the release page.
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/811443dc-af0f-408f-bf8e-20f5d9d8c54d)

**Comment by lvca** [comment] 2023-10-07 13:55
The issue is still about locking. (1) Could you please run `jps` on the shell and see if there is another instance of the server running?

(2) Another attempt could be moving the arcadedb distro under a path without spaces to see if that's the issue.

**Comment by JoJ123** [comment] 2023-10-08 10:43
(2) No change in folder without spaces.

(1) When I start like above I just see one entry in the list 
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/3346a374-866f-4415-8400-322b80dcc4ea)

One thought about the locking.
With other databases for gremlin server the start was not with a .bat file from the database itself. For example for Bitsy you start the gremlin-server.bat with a YAML Config file for Bitsy.
So my idea is, that the process from ArcadeDB "Core" is already locking the DB. So that GremlinServer cannot start and use it. Is there a way to start the GremlinServer via the gremlin-server.bat?

**Comment by lvca** [comment] 2023-10-08 17:37
Thanks for testing it. I agree that the server must "confuse" the `graph` database with 2 different paths, for some reason, so it tries to open the database the 2nd time but it's locked.

Or, perhaps, the open database is not registered correctly, but why does it work on Linux and Mac?

From your logs:
<img width="1147" alt="image" src="https://github.com/ArcadeData/arcadedb/assets/312606/8e4edbe8-17e6-4706-82f4-73ccfec4609a">

I can see the graph database was registered by using a relative path, since it looks like it's a Windows-only issue, there must be something with the way the paths are managed.

About the server, it's designed in that way, so ArcadeDB & Gremlin share the same JVM. This means there is no TCP/IP between the servers, no marshalling and unmarshalling of data, and that's why ArcadeDB should be the fastest Gremlin implementation out there :-)

Could you please turn on the FULL logs? Edit the file `config/arcadedb-log.properties` and change the level to FINE everywhere you see INFO and restart the server.

**Comment by JoJ123** [comment] 2023-10-09 06:07
I did some more tests.

First:
Even if the issue is displayed in the logs the Admin Console on localhost:2480 is reachable.
I was able to perform gremlin lang operations (add & fetch):
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/4d4c0676-988f-4107-8f20-7f56a7941533)
Is this linked to the Gremlin Server, or are you in the UI transforming the queries internally?

Second:
 I went further based on your hints regarding the paths. I have changed two things:
- `gremlin.arcadedb.directory=C:\ArcadeDB\databases\graph` (gremlin-server.properties)
- `-Darcadedb.server.databaseDirectory=C:\ArcadeDB\databases`
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/0343e3ad-3aeb-4f76-9cd8-237099499d62)

And tada :D It's working!
So you're right regarding the paths. With absolute paths, it's working fine now. Anyway, it would be probably better to continue the investigation to find a solution with relative paths as well.

**Comment by lvca** [comment] 2023-10-12 16:41
I see you changed the path to `C:\ArcadeDB\databases\graph`. So it could also be the space in the directory name you had before that is not correctly quoted from the script.

About your 1st question, the ArcadeDB server executes internally gremlin queries (and sql, cypher, etc) and returns the result in HTTP/JSON for Studio web tool.

**Comment by lvca** [comment] 2023-11-21 14:28
Closing this for now, please comment on this issue if this happens again, so I can reopen it.

**Closed by lvca** 2023-11-21 14:28 UTC
Labels: workaround-provided
