### ISSUE TITLE
Gremlin Error: "Record Not Found" after dropped a vertex. Simple reproducible example.

### ISSUE THREAD

**Issue by JoJ123** [ArcadeData/arcadedb#1328] opened 2023-11-16 13:08 UTC
### ArcadeDB Version:
`ArcadeDB Server v23.10.1-SNAPSHOT (build 186c0adb0743a94a733a512d31a17901d174f3bb/1695791343005/main)`
From Docker Image
### OS and JDK Version:
`Running on Linux 5.10.102.1-microsoft-standard-WSL2 - OpenJDK 64-Bit Server VM 11.0.20.1 (Temurin-11.0.20.1+1)`

### Expected behavior
`Query remaining vertexes possible after dropped another vertext`

### Actual behavior
`Getting an Error: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Record #13:0 not found`
My first analysis is, that it's happening if you drop a vertex that is having more than one incoming edge.

### Steps to reproduce
`Run the following gremlin query (Copy & Paste). I use gdotv for fast testing.`
```gremlin
g.addV("RG").
  property("name", "r1").
  addV("RG").
  property("name", "r2").as("member2").
  V().
  has("name", "r1").
  addE(":TEST").to("member2").
  addV("RG").
  property("name", "r3").as("member3").
  V().
  has("name", "r1").
  addE(":TEST").to("member3").
  addV("RG").
  property("name", "r4").as("member4").
  V().
  has("name", "r2").
  addE(":TEST").to("member4").
  addV("RG").
  property("name", "r5").as("member5").
  V().
  has("name", "r3").
  addE(":TEST").to("member5").
  V().
  has("name", "r4").
  addE(":TEST").to("member5").
  addV("P").
  property("name", "p1").as("member6").
  V().
  has("name", "r5").
  addE(":TEST").from("member6")
```
You will have the following graph:
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/aec6f16f-0c83-4193-805e-2ff179d5d013)

Execute the following gremlin query to remove `r4` from `r5` and all incoming vertexes with the label `P`:
```gremlin
g.V().
  has("RG", "name", "r4").
  out().
  has("RG", "name", "r5").
  as('deleteEntry').
  select('deleteEntry').
  sideEffect(in().hasLabel("P").drop()).
  sideEffect(select('deleteEntry').drop()).
  constant('deleted');
```

The drop itself will execute without an error. But afterwards you are not able anymore to query the database:
`Getting an Error: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: Record #13:0 not found`

## Second Issue (which is linked)
The above delete query is not working if you remove the select part of the query. Maybe this is related to gremlin not sure, but I wanted to add that here.
```gremlin
  select('deleteEntry').
```

**Comment by lvca** [comment] 2023-11-16 21:59
Thanks @JoJ123 for your detailed report. I'm unable to reproduce your issue. I executed both gremlin queries and after the drop this is what I got (on studio):

![image](https://github.com/ArcadeData/arcadedb/assets/312606/6cf820a1-f9d1-4a29-8012-1f2760a249dc)

And I don't see any error in the console. Do you have a particular query you're executing that returns the error?

**Comment by JoJ123** [comment] 2023-11-17 06:31
Hi @lvca,
I tried it also inside the Studio and it's running fine.

Anyway using a UI Tool like gdotv or even the gremlin Node.JS Client the issue is still happening for me.

This is the error log:
![image](https://github.com/ArcadeData/arcadedb/assets/38938791/4a771439-5cc7-4217-b57e-8c41b4ac301f)

The error is saying record not found and the id of this record is `r5` the one the was dropped in the previous call.

If I split the query into two queries instead of two `.sideEffect` it's also working fine. Maybe it's related to this?

**Comment by lvca** [comment] 2023-11-18 14:15
It's like the vertex was deleted but not the connected edges.  I'm going to try with that piece of code using remote gremlin client instead of studio (that execute the whole code server side).

**Comment by lvca** [comment] 2024-05-24 09:51
This issue has been fixed in the latest release.

**Closed by lvca** 2024-05-24 09:51 UTC
Labels: unable to reproduce, waiting for user
