### ISSUE TITLE
Improve the build system to produce a multiplatform image

### ISSUE THREAD

**Issue by arcade-player** [ArcadeData/arcadedb#412] opened 2022-05-27 06:35 UTC
## Expected behavior
Produce a multiplatform docker image using docker buildx

## Actual behavior
the build system produce a docker image just for intel arch

**Comment by kai-baumann** [comment] 2022-05-30 13:23
Can I provide a PR to resolve this issue?

**Comment by tristanradams** [comment] 2022-07-11 19:20
My team and I all use M1 macs and are blocked by this issue, is there any way we could bump up its priority?

**Comment by arcade-player** [comment] 2022-07-11 21:16
Proposed solution: move to another base image (azul) that provides arm64/v8  image as well.
I'm going to open a PR in a couple of days.

**Comment by lvca** [comment] 2023-03-21 01:42
Duplicate of #894

**Closed by lvca** 2023-03-21 01:42 UTC
Labels: bug

**Comment by lvca** [comment] 2023-05-21 20:57
@robfrank with the latest commits, it doesn't compile on my Mac:

```
[ERROR] Errors:
[ERROR]   JdbcQueriesTest » NoClassDefFound Could not initialize class com.arcadedb.e2e.ArcadeContainerTemplate
[ERROR]   RemoteDatabaseQueriesTest.simpleCypherQuery » ExceptionInInitializer
[ERROR]   RemoteDatabaseQueriesTest.simpleGremlinQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseQueriesTest
[ERROR]   RemoteDatabaseQueriesTest.simpleSQLQuery » NoClassDefFound Could not initialize class com.arcadedb.e2e.RemoteDatabaseQueriesTest
[INFO]
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0
[INFO]
```

**Comment by robfrank** [comment] 2023-05-21 21:11
I didn't touch the code . Only pom and GH workflows
