### ISSUE TITLE
Unexpected exception when comparing a counted value with a negative value

### ISSUE THREAD

**Issue by zhengyingying** [ArcadeData/arcadedb#999] opened 2023-04-03 09:17 UTC
### Expected and Actual behavior

When we query vertices whose number of incoming vertices is equal to -3, it returns an exception `Not a legal range: [0, -2]`. But when we compare the number of incoming vertices with values greater than -2, we can get the correct query result.

```
gremlin> :> g.V().where(__.in().count().is(eq(-3)))
Not a legal range: [0, -2] 

gremlin> :> g.V().where(__.in().count().is(eq(-2)))
```

**Comment by lvca** [comment] 2023-04-03 17:26
I was able to reproduce it. Weird. Working on it.

**Comment by lvca** [comment] 2023-04-03 17:31
I see this is Gremlin code. I bet the same happens with all the DBMS that uses Gremlin stack. @zhengyingying have you tried with TinkerGraph?

**Comment by zhengyingying** [comment] 2023-04-04 01:24
@lvca Thanks for your replay. 
I found that TinkerGraph also has this bug. I've submitted an issue to its community.

**Comment by lvca** [comment] 2023-04-04 02:16
Closing the issue here because it's part of the Gremlin stack.

**Closed by lvca** 2023-04-04 02:16 UTC
Labels: bug
