### ISSUE TITLE
SchemaException thrown when using hasLabel() as edge filter and the label doesn't exist

### ISSUE THREAD

**Issue by marco-brandizi** [ArcadeData/arcadedb#1594] opened 2024-05-11 16:45 UTC
### ArcadeDB Version:

24.4.1

### OS and JDK Version:

* Java: OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)

* OS: Linux NAME = "Rocky Linux 8.7"

### Expected behavior

I still see #193: In Gremlin, when using `hasLabel()` with a non existing parameter value, an empty result is expected. This should return nulls:

```groovy
g.V().hasLabel ( 'foo-label' ).count ()
g.E().hasLabel ( 'foo-label' ).count ()
```

### Actual behavior

Both the queries above (when executed against a DB without that label) return something like: 

`com.arcadedb.exception.SchemaException: Type with name 'is_a_1' was not found`

This happens both when using the Studio and the Java driver. Interestengly, without the `.count()` step, it silently returns the expected empty results.

### Steps to reproduce

See above.

**Comment by lvca** [comment] 2024-05-11 20:47
Thanks for the report, the issue is fixed now in the latest `24.5.1-SNAPSHOT`.

**Closed by lvca** 2024-05-11 20:47 UTC
Labels: bug
