### ISSUE TITLE
SQL BACKUP DATABASE not working

### ISSUE THREAD

**Issue by allegrojm** [ArcadeData/arcadedb#898] opened 2023-02-26 18:48 UTC
### OS: CentOS Linux 7 (Core)

The database backup SQL command BACKUP DATABASE is not working for us. We have a 3-server HA database cluster setup.  But not sure if that is relevant. Tried the backup command from studio as well as using the HTTP API.

## Expected behavior
A properly created database backup zip file

## Actual behavior
When we issue the BACKUP DATABASE command all we get is the following message in the log:

023-02-26 16:31:00.783 SEVER [BackupDatabaseStatement] <OhioServer> Found pending transaction. Rolling it back before the backup...
2023-02-26 16:31:01.084 SEVER [CodeUtils] <OhioServer> Error during suspend flush

and an empty zip file in the backups directory.

## Steps to reproduce

SQL command BACKUP DATABASE with active HA cluster

**Comment by lvca** [comment] 2023-02-27 20:34
Are you executing the backup against the leader?

**Comment by allegrojm** [comment] 2023-02-27 20:54
Yes, the server that received the backup command was the leader. But, since Arcadedb doesn't have an automatic backup capability right now, we were preparing to set up a nightly cron to have a script run that does the backup. This though might not work if the script needs to be running on the leader.

**Comment by allegrojm** [comment] 2023-02-27 20:56
... meaning the script doesn't know if it's running on the leader server or not.

**Comment by lvca** [comment] 2023-02-28 22:30
@allegrojm I've just pushed on main a fix to dump the exception in case of a backup error. Could you please retry with the latest snapshot built from sources? Thanks in advance.

**Comment by allegrojm** [comment] 2023-02-28 22:59
Will do. Will post here when we have an update.

**Comment by allegrojm** [comment] 2023-03-01 20:55
Updated to latest snapshot. Ran the backup database command. Here's the exception:

2023-03-01 20:50:34.876 SEVER [BackupDatabaseStatement] <OhioServer> Found pending transaction. Rolling it back before the backup...<OhioServer> Error during suspend flush
java.lang.ClassCastException: class com.arcadedb.server.ha.ReplicatedDatabase cannot be cast to class com.arcadedb.database.EmbeddedDatabase (com.arcadedb.server.ha.ReplicatedDatabase and com.arcadedb.database.EmbeddedDatabase are in unnamed module of loader 'app')
	at com.arcadedb.integration.backup.format.FullBackupFormat.lambda$backupDatabase$0(FullBackupFormat.java:79)
	at com.arcadedb.utility.CodeUtils.executeIgnoringExceptions(CodeUtils.java:32)
	at com.arcadedb.engine.PageManager.suspendFlushAndExecute(PageManager.java:138)
	at com.arcadedb.integration.backup.format.FullBackupFormat.lambda$backupDatabase$1(FullBackupFormat.java:74)
	at com.arcadedb.database.EmbeddedDatabase.executeInReadLock(EmbeddedDatabase.java:1298)
	at com.arcadedb.server.ha.ReplicatedDatabase.executeInReadLock(ReplicatedDatabase.java:621)
	at com.arcadedb.integration.backup.format.FullBackupFormat.backupDatabase(FullBackupFormat.java:72)
	at com.arcadedb.integration.backup.Backup.backupDatabase(Backup.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.arcadedb.query.sql.parser.BackupDatabaseStatement.executeSimple(BackupDatabaseStatement.java:62)
	at com.arcadedb.query.sql.executor.SingleOpExecutionPlan.executeInternal(SingleOpExecutionPlan.java:91)
	at com.arcadedb.query.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:55)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.doExecute(ScriptExecutionPlan.java:95)
	at com.arcadedb.query.sql.executor.ScriptExecutionPlan.fetchNext(ScriptExecutionPlan.java:59)
	at com.arcadedb.query.sql.parser.LocalResultSet.fetchNext(LocalResultSet.java:45)
	at com.arcadedb.query.sql.parser.LocalResultSet.<init>(LocalResultSet.java:39)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.executeInternal(SQLScriptQueryEngine.java:176)
	at com.arcadedb.query.sql.SQLScriptQueryEngine.command(SQLScriptQueryEngine.java:106)
	at com.arcadedb.database.EmbeddedDatabase.command(EmbeddedDatabase.java:1236)
	at com.arcadedb.server.ha.ReplicatedDatabase.command(ReplicatedDatabase.java:594)
	at com.arcadedb.server.ServerDatabase.command(ServerDatabase.java:416)
	at com.arcadedb.server.http.handler.PostCommandHandler.executeScript(PostCommandHandler.java:118)
	at com.arcadedb.server.http.handler.PostCommandHandler.execute(PostCommandHandler.java:87)
	at com.arcadedb.server.http.handler.DatabaseAbstractHandler.execute(DatabaseAbstractHandler.java:92)
	at com.arcadedb.server.http.handler.AbstractHandler.handleRequest(AbstractHandler.java:128)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by lvca** [comment] 2023-03-01 23:39
That was very helpful, thanks! The issue is fixed in `main` branch.

**Closed by lvca** 2023-03-01 23:39 UTC
Labels: bug
