### ISSUE TITLE
Restore file not found

### ISSUE THREAD

**Issue by tmcsys** [ArcadeData/arcadedb#1384] opened 2023-12-17 15:49 UTC
ArcadeDB Server v23.11.1 (build 798b2b6f581bb4e6017535815dc3257f72c5fd81/1701318772588/main) 
Running on Mac OS X 13.6 - OpenJDK 64-Bit Server VM 17.0.9 (Temurin-17.0.9+9)

This has been a real barrier to entry.  

From server directory:

arcadedb-23.11.1 % bin/restore.sh -f backups/Movies-backup-20211005-134613862.zip -d ArcadeMovies
Exception in thread "main" com.arcadedb.integration.restore.RestoreException: Error during restore of database from file 'backups/Movies-backup-20211005-134613862.zip'
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:58)
	at com.arcadedb.integration.restore.Restore.main(Restore.java:45)
Caused by: com.arcadedb.integration.restore.RestoreException: **The backup file 'backups/Movies-backup-20211005-134613862.zip' not exist**
	at com.arcadedb.integration.restore.format.FullRestoreFormat.openInputFile(FullRestoreFormat.java:135)
	at com.arcadedb.integration.restore.format.FullRestoreFormat.restoreDatabase(FullRestoreFormat.java:53)
	at com.arcadedb.integration.restore.Restore.restoreDatabase(Restore.java:55)
	... 1 more

ls -l backups/Movies-backup-20211005-134613862.zip
-rw-r--r--@ 1 me  staff  38852 Dec 17 09:39 backups/Movies-backup-20211005-134613862.zip

### Steps to reproduce

1) clone arcadedb-datasets
2) move arcadedb/Movies-backup-20211005-134613862.zip to [server_root]/backups
3) cd to [server_root]
4) execute bin/restore.sh -f backups/Movies-backup-20211005-134613862.zip -d ArcadeMovies

**Comment by lvca** [comment] 2023-12-17 16:45
What github project is "arcadedb-datasets"?

**Comment by lvca** [comment] 2023-12-17 16:54
Nevermind, I was able to reproduce with any backup. The issue must be in the `restore.sh` script configuration. Working on it

**Comment by lvca** [comment] 2023-12-17 17:15
The issue is on line 37 of restore.sh script:

```
cd "$ARCADEDB_HOME/bin"
```

Just pushed a fix, but If you simply remove it from your distribution, it should work.

**Closed by lvca** 2023-12-17 17:15 UTC
Labels: bug

**Comment by gramian** [comment] 2023-12-17 17:18
As a workaround for a release, the [`server.defaultDatabases`](https://docs.arcadedb.com/#Settings) setting should work. There you can also use a "restore".
