### ISSUE TITLE
Server closed automatically after being idle for hours

### ISSUE THREAD

**Issue by angkor-wat** [ArcadeData/arcadedb#1043] opened 2023-04-18 02:21 UTC
### OS:  CentOS release 6.5 (Final)

Server mode: development
### Expected behavior
Keep running 

### Actual behavior
Server closed automatically after being idle for hours

**Comment by lvca** [comment] 2023-04-18 03:17
@angkor-wat do you mean the ArcadeDB Server closes the HTTP socket? Do you have the logs of the servers so we can look into it?

**Comment by angkor-wat** [comment] 2023-04-19 00:52
2023-04-18 10:21:08.465 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server v23.2.1 (build e8f512fa466c4a32ef9d14d89af20e7ac2859c7e/1677638572021/main) is starting up...
2023-04-18 10:21:08.466 INFO  [ArcadeDBServer] <ArcadeDB_0> Starting ArcadeDB Server with plugins [] ...
2023-04-18 10:21:08.487 INFO  [ArcadeDBServer] <ArcadeDB_0> - JMX Metrics Started...
2023-04-18 10:21:09.465 INFO  [HttpServer] <ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480-2489 httpsPort=2490-2499)...
2023-04-18 10:21:09.518 INFO  [undertow] starting server: Undertow - 2.3.3.Final
2023-04-18 10:21:09.527 INFO  [xnio] XNIO version 3.8.8.Final
2023-04-18 10:21:09.536 INFO  [nio] XNIO NIO Implementation Version 3.8.8.Final
2023-04-18 10:21:09.568 INFO  [threads] JBoss Threads version 3.5.0.Final
2023-04-18 10:21:09.619 INFO  [HttpServer] <ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480 httpsPort=2490)
2023-04-18 10:21:09.640 INFO  [ArcadeDBServer] <ArcadeDB_0> Available query languages: [sqlscript, mongo, gremlin, java, cypher, js, graphql, sql]
2023-04-18 10:21:09.642 INFO  [ArcadeDBServer] <ArcadeDB_0> ArcadeDB Server started in 'development' mode (CPUs=16 MAXRAM=7.78GB)
2023-04-18 10:21:09.642 INFO  [ArcadeDBServer] <ArcadeDB_0> Studio web tool available at http://localhost.localdomain:2480 
2023-04-19 01:43:17.397 INFO  [ArcadeDBServer] Shutting down ArcadeDB Server...

**Comment by angkor-wat** [comment] 2023-04-19 00:56
![log](https://user-images.githubusercontent.com/41616207/232938637-b3c7c837-4182-44fd-abb0-0c5f23683446.png)

**Comment by lvca** [comment] 2023-04-19 05:26
I don't see any issue with the log. is it possible the kernel kills the server after a while? Are you running on docker/kubernetes?

**Comment by angkor-wat** [comment] 2023-04-19 06:01
not running on docker/kubernetes

**Comment by lvca** [comment] 2023-04-25 03:59
I'm unable to reproduce it. Tried to keep the server idle for more than 24h, no problem. Is it possible something in your computer killed the process?

**Comment by lvca** [comment] 2023-06-09 00:45
Any news on this? Closing this issue as resolved. In case please comment here to be reopened.

**Closed by lvca** 2023-06-09 00:45 UTC
Labels: unable to reproduce, waiting for user
